BEGIN;

CREATE TABLE properties (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  property JSONB NOT NULL,
  location point
);

CREATE TABLE locations (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  location point NOT NULL
);

COMMIT;

UPDATE properties SET location = locations.location FROM locations WHERE properties.id = locations.id;