BEGIN;

CREATE TABLE properties (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  property JSONB NOT NULL,
  location point
);

CREATE TABLE coordinates (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  coordinates point NOT NULL
);

COMMIT;

UPDATE properties 
SET location = coordinates.coordinates 
FROM coordinates 
WHERE properties.id = coordinates.id;